In [2]:
# pip install numpy

In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,4]
arr=np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4]


In [7]:
arr.shape

(4,)

In [8]:
arr.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [72]:
my_list1=[1,2,3,4,5]
my_list2=[5,2,3,4,5]
my_list3=[7,2,3,4,5]
arr=np.array([my_list1,my_list2,my_list3])

In [31]:
arr

array([[1, 2, 3, 4, 5],
       [5, 2, 3, 4, 5],
       [7, 2, 3, 4, 5]])

In [11]:
arr.shape

(3, 5)

In [ ]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [2, 3, 4],
       [5, 7, 2],
       [3, 4, 5]])

In [32]:
arr.shape

(3, 5)

In [49]:
arr

array([[1, 2, 3, 4, 5],
       [5, 2, 3, 4, 5],
       [7, 2, 3, 4, 5]])

In [47]:
arr[0:2,0:2]

array([[1, 2],
       [5, 2]])

In [51]:
arr[1:,3:]

array([[4, 5],
       [4, 5]])

In [73]:
arr[1:,2:4]

array([[3, 4],
       [3, 4]])

In [ ]:
arr=np.arange(0,10,step=2)
# array([0, 2, 4, 6, 8])

In [79]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
arr.reshape(1,15)
# 


array([[1, 2, 3, 4, 5, 5, 2, 3, 4, 5, 7, 2, 3, 4, 5]])

In [64]:
arr.shape

(3, 5)

INDEXING

In [65]:
arr1=np.array([1,2,3,4,5,6,7,8,9])

In [81]:
arr1[3]

np.int64(4)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [83]:
arr2 =np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
# copy function and btaodcasting
arr2[4:]=100
arr2

array([  1,   2,   3,   4, 100, 100, 100, 100, 100])

## conditions is useful for exploratory data analysis (EDA) and data visualization.

In [103]:
val=2
arr2*2


array([  2,   4,   6,   8, 200, 200, 200, 200, 200])

In [102]:
val=2
arr2<2
arr2[arr2<2]

array([1])

In [94]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [104]:
arr3 =np.arange(0,10).reshape(1,10)
arr3

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
arr2 * arr3[0, :9]

array([  0,   2,   6,  12, 400, 500, 600, 700, 800])

In [107]:
np.ones(4)

array([1., 1., 1., 1.])

In [109]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [110]:
np.random.rand(3,3)

array([[0.81686835, 0.66449606, 0.63661201],
       [0.78126011, 0.4676943 , 0.5515459 ],
       [0.38265338, 0.48533443, 0.02126405]])

In [111]:
np.random.randn(3,3)

array([[ 1.22278823,  0.22959055, -0.46323736],
       [-0.20756595,  1.2528284 , -0.85355472],
       [ 1.80816351,  0.11805614, -1.56255727]])

In [114]:
np.random.randint(0,100,8).reshape(2,4)

array([[56, 96, 93, 67],
       [55, 83,  0, 78]], dtype=int32)